{
  "id": "/docker-compose-executor-test",
  "cmd": "echo hello world",
  "cpus": 1,
  "mem": 64,
  "disk": 0,
  "instances": 1,
  "executor": "/opt/docker-compose-executor/docker-compose-executor.sh",
  "labels": {
    "fileName": "docker-compose.yml"
  },
  "portDefinitions": [
    {
      "port": 10001,
      "protocol": "tcp",
      "labels": {}
    },
    {
      "port": 10002,
      "protocol": "tcp",
      "labels": {}
    }
  ],
  "uris": [
    "https://raw.githubusercontent.com/fragoi/docker-compose-executor-test/master/docker-compose.yml"
  ],
  "fetch": [
    {
      "uri": "https://raw.githubusercontent.com/fragoi/docker-compose-executor-test/master/docker-compose.yml",
      "extract": false,
      "executable": false,
      "cache": false
    }
  ]
}
